sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: isnYran1nult
  alioss:
    endpoint: oss-ap-southeast-2.aliyuncs.com
    access-key-id: LTAI5tAYTEghGgJZ2VSq4peS
    access-key-secret: mGFDNFTeSxiDCa3N9xUGEa3nnOKMJY
    bucket-name: image-management